# captainVersion: 4
# caproverOneClickApp:
#     instructions:
#         start: Just a plain Docker Compose.
#         end: Docker Compose is deployed.
########

version: "3.0"

services:

  adventure-time-ui:
    # image: yellowranger/capstone-adventure-time:ui
    image: 177723100114.dkr.ecr.us-east-1.amazonaws.com/adventure-time-ui
    ports:
      - "80:80"
    depends_on:
      - adventure-time-api

  adventure-time-api:
    # image: yellowranger/capstone-adventure-time:api
    image: 177723100114.dkr.ecr.us-east-1.amazonaws.com/adventure-time-api
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://adventure-time-db.chr04liwekaz.us-east-1.rds.amazonaws.com/adventure_time
      - DB_USERNAME=root
      - DB_PASSWORD=soccerBalls
      - ALLOWED_ORIGINS=*
      