version: "3.0"

services:

  adventure-time-ui:
    image: adventure-time-ui
    # build: 
    #   context: adventure-time-ui
    #   dockerfile: ./client
    # image: 177723100114.dkr.ecr.us-east-1.amazonaws.com/adventure-time-ui
    ports:
      - "80:80"
    restart: always
    depends_on:
      - adventure-time-api

  adventure-time-api:
    image: adventure-time-api
    # image: 177723100114.dkr.ecr.us-east-1.amazonaws.com/adventure-time-api
    ports:
      - "8080:8080"
    container_name: adventure-time-api
    restart: always
    environment:
      - DB_URL=jdbc:mysql://adventure-time-db.chr04liwekaz.us-east-1.rds.amazonaws.com/adventure_time
      - DB_USERNAME=root
      - DB_PASSWORD=soccerBalls
      - AWS-ACCESS-KEY=AKIASSYI7JPJKSTDGSWX
      - AWS-SECRET-KEY=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
      - ALLOWED_ORIGINS=*
      